"""empty message

Revision ID: 56ba6e293af7
Revises: d4867f3a4c0a
Create Date: 2021-07-30 06:58:56.301191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ba6e293af7'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('min_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_category_id'), 'weight_category', ['id'], unique=False)
    op.create_index(op.f('ix_weight_category_title'), 'weight_category', ['title'], unique=False)

    op.create_table('fighter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('weight_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weight_category_id'], ['weight_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fighter_first_name'), 'fighter', ['first_name'], unique=False)
    op.create_index(op.f('ix_fighter_id'), 'fighter', ['id'], unique=False)
    op.create_index(op.f('ix_fighter_last_name'), 'fighter', ['last_name'], unique=False)

    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_fighter_id', sa.Integer(), nullable=False),
    sa.Column('second_fighter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_fighter_id'], ['fighter.id'], ),
    sa.ForeignKeyConstraint(['second_fighter_id'], ['fighter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)



def downgrade():
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_fighter_last_name'), table_name='fighter')
    op.drop_index(op.f('ix_fighter_id'), table_name='fighter')
    op.drop_index(op.f('ix_fighter_first_name'), table_name='fighter')
    op.drop_table('fighter')
    op.drop_index(op.f('ix_weight_category_title'), table_name='weight_category')
    op.drop_index(op.f('ix_weight_category_id'), table_name='weight_category')
    op.drop_table('weight_category')
